name: 'Hello World'

description: 'Greet the world'
author: "@mmadiawetsa"

input:
  myInput:
  description: "inqput to use"
  default: "world"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
